version: '3'
services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - LLM_API_ENDPOINT=${LLM_API_ENDPOINT}
      - LLM_API_KEY=${LLM_API_KEY}
      - POWERED_BY=${POWERED_BY}
      - DAILY_REQUEST_LIMIT=${DAILY_REQUEST_LIMIT}
      - COPYRIGHT_YEAR=${COPYRIGHT_YEAR}
      - COPYRIGHT_OWNER=${COPYRIGHT_OWNER}
      - PRIVACY_POLICY_URL=${PRIVACY_POLICY_URL}
    restart: always
